/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from backend Pydantic schemas.
 * Run `python scripts/generate_types.py` to regenerate.
 *
 * Source: src/api/schemas.py
 * Generated: 2026-02-03T15:25:27.782597
 */

/**
 * Request schema for voice synthesis.
 */
export interface VoiceSynthesizeRequest {
  text?: string;
  backend?: string;
  speaker_wav?: string | null;
  device?: string;
}

/**
 * Response schema for voice synthesis.
 */
export interface VoiceSynthesizeResponse {
  audio_path?: string;
  duration?: number;
  backend?: string;
  text_length?: number;
}

/**
 * Request schema for creating voice profile.
 */
export interface VoiceProfileCreateRequest {
  name?: string;
  sample_paths?: string[];
  description?: string | null;
  metadata?: Record<string, any> | null;
}

/**
 * Response schema for voice profile.
 */
export interface VoiceProfileResponse {
  name?: string;
  description?: string | null;
  sample_count?: number;
  created_at?: string;
  metadata?: Record<string, any> | null;
}

/**
 * Response schema for listing voice profiles.
 */
export interface VoiceProfileListResponse {
  profiles?: string[];
  count?: number;
}

/**
 * Error response schema.
 */
export interface ErrorResponse {
  error?: string;
  detail?: string | null;
}

/**
 * Request schema for user registration.
 */
export interface UserRegisterRequest {
  username?: string;
  email?: string;
  password?: string;
}

/**
 * Request schema for user login.
 */
export interface UserLoginRequest {
  username?: string;
  password?: string;
}

/**
 * Response schema for authentication tokens.
 */
export interface TokenResponse {
  access_token?: string;
  refresh_token?: string;
  token_type?: string;
  expires_in?: number;
  user?: 'UserResponse' | null;
}

/**
 * Request schema for token refresh.
 */
export interface TokenRefreshRequest {
  refresh_token?: string;
}

/**
 * Response schema for user information.
 */
export interface UserResponse {
  id?: number;
  username?: string;
  email?: string;
  is_active?: boolean;
  is_superuser?: boolean;
  created_at?: string;
}

/**
 * Request schema for creating a digital human.

Note: The actual API endpoint accepts multipart/form-data with:
- name: str (Form field)
- description: Optional[str] (Form field)
- image: UploadFile (File upload)
- voice_model_path: Optional[str] (Form field)
 */
export interface DigitalHumanCreateRequest {
  name?: string;
  description?: string | null;
  voice_model_path?: string | null;
}

/**
 * Response schema for digital human.
 */
export interface DigitalHumanResponse {
  id?: number;
  user_id?: number;
  name?: string;
  description?: string | null;
  image_path?: string | null;
  voice_model_path?: string | null;
  video_path?: string | null;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

/**
 * Response schema for listing digital humans.
 */
export interface DigitalHumanListResponse {
  digital_humans?: DigitalHumanResponse[];
  total?: number;
}

/**
 * Request schema for video generation.

Note: The actual API endpoint accepts multipart/form-data with:
- digital_human_id: int (Form field)
- text: Optional[str] (Form field, for text-to-video)
- audio: Optional[UploadFile] (File upload, for audio-to-video)
- mode: str (Form field, default: "enhanced_talking_head")
 */
export interface VideoGenerateRequest {
  digital_human_id?: number;
  text?: string | null;
  mode?: string;
}

/**
 * Response schema for video generation.
 */
export interface VideoGenerateResponse {
  video_path?: string;
  digital_human_id?: number;
  mode?: string;
  message?: string;
}

/**
 * Plugin information schema.
 */
export interface PluginInfo {
  name?: string;
  version?: string;
  dependencies?: string[];
}

/**
 * Response schema for listing plugins.
 */
export interface PluginListResponse {
  plugins?: PluginInfo[];
  total?: number;
}

/**
 * Request schema for installing a plugin.
 */
export interface PluginInstallRequest {
  name?: string;
}

/**
 * Response schema for plugin installation.
 */
export interface PluginInstallResponse {
  name?: string;
  version?: string;
  message?: string;
}

/**
 * Request schema for reloading a plugin.
 */
export interface PluginReloadRequest {
  name?: string;
}

/**
 * Response schema for plugin reload.
 */
export interface PluginReloadResponse {
  name?: string;
  version?: string;
  message?: string;
}

/**
 * Request schema for creating an agent.
 */
export interface AgentCreateRequest {
  name?: string;
  system_prompt?: string;
  capabilities?: string[];
}

/**
 * Request schema for updating an agent.
 */
export interface AgentUpdateRequest {
  system_prompt?: string | null;
  capabilities?: string[] | null;
}

/**
 * Response schema for agent information.
 */
export interface AgentResponse {
  name?: string;
  system_prompt?: string;
  capabilities?: string[];
}

/**
 * Response schema for listing agents.
 */
export interface AgentListResponse {
  agents?: AgentResponse[];
  total?: number;
}

/**
 * Request schema for creating a task.
 */
export interface TaskCreateRequest {
  name?: string;
  description?: string | null;
  task_type?: string;
  schedule?: string | null;
  params?: Record<string, any> | null;
}

/**
 * Request schema for updating a task.
 */
export interface TaskUpdateRequest {
  name?: string | null;
  description?: string | null;
  schedule?: string | null;
  params?: Record<string, any> | null;
  status?: string | null;
}

/**
 * Response schema for task information.
 */
export interface TaskResponse {
  id?: number;
  user_id?: number;
  name?: string;
  description?: string | null;
  task_type?: string;
  schedule?: string | null;
  params?: Record<string, any> | null;
  status?: string;
  result?: Record<string, any> | null;
  error_message?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  created_at?: string;
  updated_at?: string;
}

/**
 * Response schema for listing tasks.
 */
export interface TaskListResponse {
  tasks?: TaskResponse[];
  total?: number;
}
